networks:
  shared-network:
    name: ${SHARED_DOCKER_NETWORK}
    external: true
  agent_network:
    driver: bridge

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: /storage/portainer/data
      o: bind

services:
  agent:
    image: portainer/agent:latest
    container_name: portainer-agent
    restart: always
    ports:
      - "${PORTAINER_AGENT_PORT}:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    environment:
      - EDGE=1
      - EDGE_ID=${PORTAINER_EDGE_ID}
      - EDGE_KEY=${PORTAINER_EDGE_KEY}
      - EDGE_INSECURE_POLL=${PORTAINER_EDGE_INSECURE_POLL}
      - LOG_LEVEL=${PORTAINER_LOG_LEVEL}
    networks:
      - agent_network
      - shared-network
