networks:
  shared-network:
    name: ${SHARED_DOCKER_NETWORK}
    external: true

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: /storage/portainer/data
      o: bind

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    networks:
      - shared-network
    restart: always
    ports:
      - "${PORTAINER_PORT}:9000"   # Portainer web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   # Docker socket
      - portainer_data:/data                        # Persistent Portainer data
