networks:
  shared-network:
    name: ${SHARED_DOCKER_NETWORK}
    external: true
  agent_network:
    driver: overlay

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: /storage/portainer/data
      o: bind

services:
  agent:
    image: portainer/agent:latest
    container_name: portainer-agent
    restart: always
    ports:
      - "${PORTAINER_AGENT_PORT}:9001"
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
      - shared-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
